kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  namespace: semantic-search
  labels:
    type: local  # local persistent volume
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: semantic-search
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50M
