kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  namespace: semantic-search
  labels:
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: semantic-search
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
