apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: semantic-search
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
